### ISSUE TITLE
Plugin does not work on Windows

### ISSUE THREAD

**Issue by RajkumarPatange** [IBM-UrbanCode/Gradle-UCB#1]
# Plugin is not working on windows : below Message appears and nothing happens

 The system cannot find the path specified.

 ================================================================================
 Post Processing Script Execution Console Output:

**Comment by nhmathis** [comment]
Hi @RajkumarPatange,

This is a very odd error as the plugin should not be displaying any of this output.  Would you mind posting more of your error log? Have you made any edits to the plugin?

The initial error indicates that a folder/file is not found. Is Gradle installed on the Agent's host? Does a gradle file exist in the project folder's base directory?

Regards,
Nick

**Comment by RajkumarPatange** [comment]
Hi Nick,

Issue with => env/GROOVY_HOME variable referred in plugin.xml .when we
change to GROOVY_HOME it starts working !
Found out after some iteration

<command program="${env/GROOVY_HOME}/bin/groovy">
        <arg value="-cp" />
        <arg path="classes:lib/groovy-plugin-utils-1.0.jar" />
        <arg file="gradle.groovy" />
        <arg file="${PLUGIN_INPUT_PROPS}"/>
        <arg file="${PLUGIN_OUTPUT_PROPS}"/>
      </command>
